# Generated by Django 3.2 on 2022-05-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220530_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stlye',
            new_name='style',
        ),
    ]
