# Generated by Django 3.2 on 2022-06-15 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='style',
            new_name='country',
        ),
    ]
