# Generated by Django 3.2 on 2022-06-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20220620_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ABV',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
