# Generated by Django 3.2 on 2022-06-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20220623_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ABV',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
